spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: bolbona
  jpa:
    show-sql: true
  security:
    user:
      name: rohan
      password: bolbona
      
server:
  servlet:
    context-path: /productapi
    
productrestapi:
  services:
    url: http://localhost:8080/productapi/products/
    
logging:
  file:
    name: logs/application.log
  level:
    root: info
    '[com.rohan.springweb.controllers.ProductRestController]': error
  logback:
    rollingpolicy:
      max-history: 3
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
            
springdoc:
  swagger-ui:
    path: /swaggerui    
    